name: Run Parser/Interpreter Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Make and populate build directory
      run: mkdir -p build && cd build && cmake .. && make
    - name: Run tests
      run: ./test_runner
